### ISSUE TITLE
Redesign app

### ISSUE THREAD

**Issue by ikkentim** [ParkitectNexus/ParkitectNexusClient#11]
- [x] An slick an clear design
- [x] A design which suits it's platform (a native look-and-feel)
- [x] All features should be easily accessible
- [x] Tile based overview of installed mods, blueprints and saves

Create and test for
- [x] Windows
- [x] Max OSX
- [x] Linux

**Comment by pollend** [comment]
could you mock up a design for the application. I can look into adding these features to the linux client.

**Comment by ikkentim** [comment]
@pollend I only got some vague ideas so far. It's not a top priority item. Pre-Alpha 6 is likely to be released before the redesigning will be complete, therefore we'll ship the Linux client as you PR'd it.

I'll post some mockups once I start working on this issue :)

**Comment by ikkentim** [comment]
What it currently looks like (subject to change) ![](http://i.imgur.com/hQOwLg4.gif)

**Comment by pollend** [comment]
This looks really good.

**Comment by pollend** [comment]
Here is the look for the linux client. most of the changes were in terms of the codebase. I'm not quite sure how to change the look of the UI itself. i'm on kde so it looks this way but, this will look different depending on the distribution of linux. the binding for gtk and C# is not too particularly good, but it's workable which is good. I'll have to do a bit of research, but i can atleast say that this version of the client is a lot more portable then the other one I made. It should be pretty easy to swap out and change the UI.

![snapshot2](https://cloud.githubusercontent.com/assets/854359/12219324/bfb69292-b6f3-11e5-9f89-bc05a3e2c7c2.png)

**Comment by ikkentim** [comment]
I've been rewriting the frontend using XWT... It's taking some time, but there's profit all over.
