### ISSUE TITLE
Optimize code for unit tests

### ISSUE THREAD

**Issue by ikkentim** [ParkitectNexus/ParkitectNexusClient#16]
See #14

**Comment by pollend** [comment]
I've been looking at http://structuremap.github.io/software-design-concepts/ . This is a pretty interesting library we can look into using. All of our service dependent items such as calls to the web, file calls, and operating system dependent items can be routed through a container we pass around. In terms of unit testing we can inject a mock service into the classes we want to test. I still need to play around with the library a bit more and figure out a format. I was thinking at looking at MVVM and MVC patterns associated with this ioc container approach.

**Comment by pollend** [comment]
I've started developing this for this given feature. I'm looking into using an Ioc container to manage dependencies. everything will be injected into the constructor and the ioc container will manage the dependencies. What do you think about this?

This should demonstrate this quite nicely: http://structuremap.github.io/the-container/auto-wiring/

https://github.com/pollend/ParkitectNexusClient/tree/feature-16_1

**Comment by pollend** [comment]
So i manage to get the window's client to build with an ioc container. The UI itself still needs to function through the container which is still a problem. I just hacked together a containing class and passed in the dependencies using the container.

 Tell me what you think of these changes. the good thing about this structure is that everything is loosely bounded which means that testing is incredibly easy. There are a lot of changes to the overall project so i rather not add this in as a pull request.

https://github.com/pollend/ParkitectNexusClient/tree/feature-16_1

**Comment by ikkentim** [comment]
See #16
