### ISSUE TITLE
installation requires administration right

### ISSUE THREAD

**Issue by mathlusiverse** [ParkitectNexus/ParkitectNexusClient#2]
The installation requires administrative right on my Windows PC.
I change the default installation directory 'C:\Program Files (x86)\ParkitectNexus Client\' to something else; it still say I don't have sufficient privileges to access the directory
'\\admshare\General Applications\Programs\ParkitectNexus Client\' <--- don't know where this path come from.

The actual game 'Parkitect.exe' doesn't require any installation, I can run it directly without any problem. Can you please consider building a non-msi version of ParkitectNexus Client?

**Comment by ikkentim** [comment]
I've never heard of that directory, nor can I find it on internet. 

What version of windows are you running?  
Can you try turning down your UAC level and installing the client again?

**Comment by mathlusiverse** [comment]
@ikkentim, thanks for looking into the matter.  My OS is Windows 7 Professional. The computers are administrated by someone else. May be the directory were setup by administrator to save all app data. I can't turn off UAC level.

**Comment by ikkentim** [comment]
Ah I see, the problem is you don't have administrator permissions. I think this will also become an issue when launching mods.

Here are the binaries so you can give it at try: https://www.dropbox.com/s/dqes3spf4y5eiq4/ParkitectNexus%20Client.zip?dl=0

**Comment by mathlusiverse** [comment]
The binaries work and I am able to install mods from the parkitectnexus.com by clicking "Install with ParkitectNexus Client". Everything goes smoothly. I started the Parkitect and am playing with your guest-cam mod now. It works correctly!  

I enjoy your mods, Thanks!

**Comment by luukholleman** [comment]
How come that you don't have admin rights? Can't the administrator install it for you?

**Comment by skypatcher** [comment]
The PC is managed by others, and is for my exclusive use.
