### ISSUE TITLE
xdg-open issue with browser

### ISSUE THREAD

**Issue by pollend** [ParkitectNexus/ParkitectNexusClient#21]
So for the linux client this command will fail with invalid characters. From what I see it doesn't like spaces, plus signs, percent signs, etc... I at least managed to get the .desktop icon to work in linux, but the url feature won't work with the way these urls are encoded. Is it possible to send a hash over instead of this url, maybe change the way the url's are encoded to work around this limitation. there are quite a few way to go about this, but just make sure to test this in terminal.

maybe it can work the same way steam does ex : steam://rungameid/214490
ex: parkitectnexus://asdfnja893md9nd
xdg-open 'parkitectnexus://Tropical&Trees+Pack\mod\RenaleTropical&Trees+Pack\mod\Renaleteto2Fparkitect-tropical-trees-pack'

**Comment by ikkentim** [comment]
Hmm I liked the simplicity and readability. Once I have the time I'll look into this and what the heck xdg-open actually is.

**Comment by pollend** [comment]
https://wiki.archlinux.org/index.php/xdg-open

**Comment by ikkentim** [comment]
Replaced by #28, which as already been closed.
