### ISSUE TITLE
refactoring data-layer

### ISSUE THREAD

**Issue by pollend** [ParkitectNexus/ParkitectNexusClient#22]
I want to re-factor the data layer a bit to clean up the code more. the way I configure the container might not be the best way, but it's workable. I want to hear your opinion in terms of moving things around to make more sense.

**Comment by ikkentim** [comment]
I'm currently moving things around myself, so it'd be better if you didn't. We have loads of idea that involve additional data.

Are there any major things you would you have done differently and that I should consider?

**Comment by pollend** [comment]
i want to move asset-magic to the data layer as well as the gamedata model and all the utilities that is for the most part copied from platform to platform. I just want to make the UI layer as thin as possible.

**Comment by ikkentim** [comment]
Yea the asset magic was just in that client so I could quickly mock something up. that will move to the data layer.

Indeed as much as possible should move from the front-end to the data layer.
