### ISSUE TITLE
Choose a License

### ISSUE THREAD

**Issue by ikkentim** [ParkitectNexus/ParkitectNexusClient#32]
http://choosealicense.com/

**Comment by NoXPhasma** [comment]
I prefer GPL v2, but MIT is also a good license for this project.

**Comment by ikkentim** [comment]
@NoXPhasma Any reason not to choose for GPL v3?

**Comment by NoXPhasma** [comment]
@ikkentim No, GPL v3 is fine too, but I don't really see any advantages for your project over GPL v2.
