### ISSUE TITLE
Do not only report e.message() for exception logging.

### ISSUE THREAD

**Issue by dredhorse** [ParkitectNexus/ParkitectNexusClient#51]
Hi,

looks like e.message() doesn't report enough information really to troubleshoot issues (BetterPerspectiveCamera not loading in OSX for example)

Would be nice if you could report the full stack, perhaps even with a --debug switch.

**Comment by ikkentim** [comment]
Sounds like a good idea, I'll look into this for version 2.1

**Comment by ikkentim** [comment]
@dredhorse I was a little mistaken. Which logs are you talking about? The one that shows up on the tasks page? A little more detailed error report is already logged to the ParkitectNexusClient's log file at ~/.local/ParkitectNexus (I can't remember the path of the top of my head, somewhere in ~/.local). Would this suffice?
