### ISSUE TITLE
Asset is not installed after startup on OSX

### ISSUE THREAD

**Issue by luukholleman** [ParkitectNexus/ParkitectNexusClient#56]
If you install an asset, for example a blueprint, it doesn't install when the client was closed when the install button was clicked. Client does install asset when client is already open.

**Comment by ikkentim** [comment]
Can confirm...

**Comment by ikkentim** [comment]
Fixed in 12feb6526ef41a3529d668c5e9a2857a5c052621 / mono/xwt#595
