### ISSUE TITLE
upgrade mono version in appimage

### ISSUE THREAD

**Issue by pollend** [ParkitectNexus/ParkitectNexusClient#61]
16-05-12 22:47:58] Info: Compile using compiler version v3.5. [16-05-12 22:47:58] Error: : 0:0: Corlib not in sync with this runtime: expected corlib version 140, found 138. in [16-05-12 22:47:58] Error: : 0:0: Loaded from: /tmp/.mount_T9Oat2/usr/lib/mono/4.5/mscorlib.dll in [16-05-12 22:47:58] Error: : 0:0: Download a newer corlib or a newer runtime at www.mono-project.com/download. in

**Comment by luukholleman** [comment]
Is it connecting with http or https?
